
package views;

import controllers.UserController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class UserManagementView extends javax.swing.JFrame {

    public static String saveMode = "edit";

    /**
     * Creates new form UserManagementView
     */
    public UserManagementView() {
        initComponents();
        lstUsers.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        lstUsers.addListSelectionListener(listSelectionListener);
        this.setLocationRelativeTo(null);
        this.listUsers();
    }
            
    @Override
    public void dispose() {
        // Do things before dispose
        super.dispose();
    }
    
    ListSelectionListener listSelectionListener = new ListSelectionListener() {
      public void valueChanged(ListSelectionEvent listSelectionEvent) {

            
          if (!listSelectionEvent.getValueIsAdjusting()) {
            String[] record = UserController.loadUser(lstUsers.getSelectedValue());
            
            if (null != record) {
                txtUsername.setText(record[0]);
                lblCreatedAt.setText(record[1]);
                lblLastLoginAt.setText(record[2]);
                
                // Initializing
                txtUsername.setEnabled(false);
                txtPassword.setEnabled(false);
                txtRetypePassword.setEnabled(false);
                lblCreatedAt.setText(" ...");
                lblLastLoginAt.setText(" ...");
                btnSave.setEnabled(false);
                btnChangePassword.setEnabled(true);
                saveMode = "edit";                 
            }
          }
      }     
    };
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtRetypePassword = new javax.swing.JPasswordField();
        btnAddNew = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCreatedAt = new javax.swing.JLabel();
        lblLastLoginAt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Management");
        setResizable(false);

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("User Management");

        txtUsername.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtUsername.setEnabled(false);
        txtUsername.setNextFocusableComponent(txtPassword);

        jLabel2.setText("Password");

        txtPassword.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtPassword.setEnabled(false);
        txtPassword.setNextFocusableComponent(txtRetypePassword);

        jLabel4.setText("Re-type Password");

        txtRetypePassword.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtRetypePassword.setEnabled(false);
        txtRetypePassword.setNextFocusableComponent(btnSave);
        txtRetypePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetypePasswordKeyPressed(evt);
            }
        });

        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnChangePassword.setText("Change Password");
        btnChangePassword.setEnabled(false);
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lstUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "User 1", "User 2", "User 3", "User 4", "User 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUsers.setNextFocusableComponent(btnAddNew);
        jScrollPane1.setViewportView(lstUsers);

        jLabel5.setText("Created At");

        jLabel6.setText("Last Login At");

        lblCreatedAt.setText(" ...");

        lblLastLoginAt.setText(" ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChangePassword)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPassword)
                                    .addComponent(txtRetypePassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCreatedAt, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(lblLastLoginAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(txtUsername))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addGap(20, 20, 20))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCreatedAt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastLoginAt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose)
                    .addComponent(btnChangePassword)
                    .addComponent(btnAddNew)
                    .addComponent(btnDelete))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listUsers() {
        DefaultListModel model = UserController.getAllUsers();
        lstUsers.clearSelection();
        lstUsers.setModel(model);
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        System.out.println("Save mode: " + saveMode);
        
        String un, pw, rpw;
        List<String> messages = new ArrayList<>();

        un = txtUsername.getText();
        pw = new String(txtPassword.getPassword());
        rpw = new String(txtRetypePassword.getPassword());
        
        if ( un.equals("") ) { messages.add("Username can't be blank"); txtUsername.grabFocus(); }
        if ( pw.equals("") ) { messages.add("Password can't be blank"); txtPassword.grabFocus(); }
        if ( rpw.equals("") ) { messages.add("Retype Password can't be blank"); txtRetypePassword.grabFocus(); }
        if ( !rpw.equals(pw) ) { messages.add("Passwords do not match"); txtRetypePassword.grabFocus(); }
        if ( !pw.equals("") && !rpw.equals("") && pw.length() < 6 ) { messages.add("Password is too short. Please enter at least 6 characters"); txtPassword.grabFocus(); }

        if (messages.size() > 0) {
            JOptionPane.showConfirmDialog(this, "The following error(s) occurred when adding the user: \n\n" + String.join("\n", messages), "User Management", JOptionPane.DEFAULT_OPTION);

        } else {
            if (UserController.addNewUser(un, pw, rpw)) {
                this.listUsers();
                JOptionPane.showConfirmDialog(this, "New user created successfully", "Add User", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                lstUsers.setSelectedIndex(lstUsers.getModel().getSize()-1);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        MainView f = new MainView();
        f.setVisible(true);          
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        txtUsername.setEnabled(true);
        txtUsername.setText("");
        txtPassword.setEnabled(true);
        txtPassword.setText("");
        txtRetypePassword.setEnabled(true);
        txtRetypePassword.setText("");
        lblCreatedAt.setText(" ...");
        lblLastLoginAt.setText(" ...");
        txtUsername.grabFocus();
        lstUsers.clearSelection();
        btnSave.setEnabled(true);
        btnChangePassword.setEnabled(false);
        saveMode = "new";
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void txtRetypePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetypePasswordKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btnSave.doClick();
        }
    }//GEN-LAST:event_txtRetypePasswordKeyPressed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure, you want to change password of the following user?\n\nUsername: " + txtUsername.getText(), "Change Password", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            JPasswordField pwdField = new JPasswordField();
            int retval = JOptionPane.showConfirmDialog(null, pwdField, "Enter new password\n(Minimum length: 4 characters)", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (retval == JOptionPane.OK_OPTION) {
                String newPassword = new String(pwdField.getPassword());

                if (newPassword.length() == 0) {
                    JOptionPane.showConfirmDialog(this, "Failed to change password.\n\nPassword can't be blank", "Change Password", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;
                    
                } else if (newPassword.length() < 4) {
                    JOptionPane.showConfirmDialog(this, "Failed to change password.\n\nPassword is too short!", "Change Password", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;                    
                }

                if (UserController.changePassword(txtUsername.getText(), newPassword)) {
                    JOptionPane.showConfirmDialog(this, "Password changed successfully", "Change Password", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreatedAt;
    private javax.swing.JLabel lblLastLoginAt;
    private javax.swing.JList<String> lstUsers;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetypePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
