
package views;

import controllers.VehicleController;
import dbpkg.DB;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


public class VehicleManagementView extends javax.swing.JFrame {

    /**
     * Creates new form VehicleManagementView
     */
    public VehicleManagementView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.loadAllVehicles();
        
        tblMain.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tblMain.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                 if (!event.getValueIsAdjusting() && tblMain.getSelectedRow() != -1) {
                    //System.out.println(tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString());
                    btnEdit.setEnabled(true);
                    btnDelete.setEnabled(true);
                 }
            }
        });
    }
    
    private void loadAllVehicles() {
        ResultSet rs = VehicleController.loadAllVehicles();
        
        try {
            DefaultTableModel tblModel = (DefaultTableModel)tblMain.getModel();
            tblModel.setRowCount(0);
                
            while(rs.next()) {
                String vehicleNo = rs.getString("vehicle_no");
                String type = rs.getString("type");
                String make = rs.getString("make");
                String model = rs.getString("model");
                String year = String.valueOf(rs.getInt("year"));
                String status = rs.getString("status");

                String tblData[] = { vehicleNo, type, make, model, year, status };
                tblModel.addRow(tblData);
            }
            
            btnEdit.setEnabled(false);
            btnDelete.setEnabled(false);            
        
        } catch (SQLException e) {
//            ERROR_MESSAGE = e.getMessage();
            
        } finally {
            DB.closeConnection();
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel3 = new javax.swing.JLabel();
                btnClose = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblMain = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                txtVehicleNo = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                txtMake = new javax.swing.JTextField();
                cboType = new javax.swing.JComboBox<>();
                jLabel4 = new javax.swing.JLabel();
                txtModel = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                txtYear = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txtEngineNo = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                txtChassisNo = new javax.swing.JTextField();
                jLabel9 = new javax.swing.JLabel();
                txtOwnerName = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                txtMileage = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                txtOwnerTel = new javax.swing.JTextField();
                jLabel12 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();
                jScrollPane2 = new javax.swing.JScrollPane();
                txtOwnerAddress = new javax.swing.JTextArea();
                jLabel13 = new javax.swing.JLabel();
                txtDailyRent = new javax.swing.JTextField();
                jLabel14 = new javax.swing.JLabel();
                txtWeeklyRent = new javax.swing.JTextField();
                jLabel15 = new javax.swing.JLabel();
                txtMonthlyRent = new javax.swing.JTextField();
                jSeparator3 = new javax.swing.JSeparator();
                btnEdit = new javax.swing.JButton();
                btnAddNew = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnView = new javax.swing.JButton();
                btnSave = new javax.swing.JButton();
                btnFind = new javax.swing.JButton();
                btnHelp = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel3.setText("Vehicle Management");
                jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

                btnClose.setText("Close");
                btnClose.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCloseActionPerformed(evt);
                        }
                });

                tblMain.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Vehicle No", "Type", "Make", "Model", "Year", "Status"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(tblMain);
                if (tblMain.getColumnModel().getColumnCount() > 0) {
                        tblMain.getColumnModel().getColumn(0).setResizable(false);
                }

                jLabel1.setText("Vehicle No");

                txtVehicleNo.setNextFocusableComponent(txtMileage);

                jLabel2.setText("Type");

                txtMake.setNextFocusableComponent(txtModel);

                cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Van", "Bus", "Truck" }));
                cboType.setNextFocusableComponent(txtVehicleNo);

                jLabel4.setText("Make");

                txtModel.setNextFocusableComponent(txtYear);

                jLabel5.setText("Model");

                jLabel6.setText("Year");

                txtYear.setNextFocusableComponent(txtEngineNo);

                jLabel7.setText("Engine No");

                txtEngineNo.setNextFocusableComponent(txtChassisNo);

                jLabel8.setText("Chassis No");

                txtChassisNo.setNextFocusableComponent(txtOwnerName);

                jLabel9.setText("Mileage (Km)");

                txtOwnerName.setNextFocusableComponent(txtOwnerTel);

                jLabel10.setText("Owner's Name");

                txtMileage.setNextFocusableComponent(txtMake);

                jLabel11.setText("Owner's Telephone");

                txtOwnerTel.setNextFocusableComponent(txtOwnerAddress);

                jLabel12.setText("Owner's Address");

                txtOwnerAddress.setColumns(20);
                txtOwnerAddress.setRows(5);
                txtOwnerAddress.setNextFocusableComponent(txtDailyRent);
                jScrollPane2.setViewportView(txtOwnerAddress);

                jLabel13.setText("Daily Rent");

                txtDailyRent.setText("0");
                txtDailyRent.setNextFocusableComponent(txtWeeklyRent);

                jLabel14.setText("Weekly Rent");

                txtWeeklyRent.setText("0");
                txtWeeklyRent.setNextFocusableComponent(txtMonthlyRent);

                jLabel15.setText("Monthly Rent");

                txtMonthlyRent.setText("0");
                txtMonthlyRent.setNextFocusableComponent(btnAddNew);

                btnEdit.setText("Edit");
                btnEdit.setEnabled(false);
                btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditActionPerformed(evt);
                        }
                });

                btnAddNew.setText("Add New");
                btnAddNew.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddNewActionPerformed(evt);
                        }
                });

                btnDelete.setText("Delete");
                btnDelete.setEnabled(false);
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnView.setText("View");
                btnView.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnViewActionPerformed(evt);
                        }
                });

                btnSave.setText("Save");
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnFind.setText("Find");
                btnFind.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnFindActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtChassisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtOwnerTel)
                                                        .addComponent(txtOwnerName)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(txtDailyRent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtMonthlyRent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtWeeklyRent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtChassisNo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9)
                                        .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtDailyRent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                .addGap(8, 8, 8)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel14)
                                                        .addComponent(txtWeeklyRent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(txtMonthlyRent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtOwnerTel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel12))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(7, 7, 7)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnEdit)
                                        .addComponent(btnDelete)
                                        .addComponent(btnView)
                                        .addComponent(btnSave)
                                        .addComponent(btnFind)
                                        .addComponent(btnAddNew))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                btnHelp.setText("Help ?");
                btnHelp.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnHelpActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnClose)
                                        .addComponent(btnHelp))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        MainView f = new MainView();
        f.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        cboType.setSelectedIndex(0);
        txtVehicleNo.setText("");
        txtMileage.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtYear.setText("");
        txtEngineNo.setText("");
        txtChassisNo.setText("");
        txtOwnerName.setText("");
        txtOwnerTel.setText("");
        txtOwnerAddress.setText("");
        txtDailyRent.setText("");
        txtWeeklyRent.setText("");
        txtMonthlyRent.setText("");
        btnSave.setEnabled(true);
        cboType.grabFocus();
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String vehicleNo = tblMain.getValueAt(tblMain.getSelectedRow(), 0).toString();
        
        if (VehicleController.deleteVehicle(vehicleNo)) {
            this.loadAllVehicles();                
            JOptionPane.showConfirmDialog(this, "Vehicle deleted successfully", "Delete Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        HashMap<String,Object> params = new HashMap<>();
        
        // Field validations
        if (txtVehicleNo.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Number can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtVehicleNo.grabFocus();
            return;
        }
        
        if (txtMileage.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Current Mileage can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtMileage.grabFocus();
            return;
        }
         
        if (txtMake.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Make can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtMake.grabFocus();
            return;
        }

        if (txtModel.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Model can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtModel.grabFocus();
            return;
        }  

        if (txtYear.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Year can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtYear.grabFocus();
            return;
        }  

        if (txtOwnerName.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Owner's Name can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtOwnerName.grabFocus();
            return;
        }  
        
        if (txtOwnerTel.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Vehicle Owner's Telepone Number can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtOwnerTel.grabFocus();
            return;
        }
        
        if (txtDailyRent.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Daily Rental amount can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtDailyRent.grabFocus();
            return;
        } 

        if (txtWeeklyRent.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Weekly Rental amount can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtWeeklyRent.grabFocus();
            return;
        } 

        if (txtMonthlyRent.getText().trim().isBlank()) {
            JOptionPane.showConfirmDialog(this, "Monthly Rental amount can't be blank", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            txtMonthlyRent.grabFocus();
            return;
        } 
        
        try {
            params.put("type", cboType.getSelectedItem());
            params.put("vehicle_no", txtVehicleNo.getText());
            params.put("mileage", Integer.parseInt(txtMileage.getText()));
            params.put("make", txtMake.getText());
            params.put("model", txtModel.getText());
            params.put("year", Integer.parseInt(txtYear.getText()));
            params.put("engine_no", txtEngineNo.getText());
            params.put("chassis_no", txtChassisNo.getText());
            params.put("owner_name", txtOwnerName.getText());
            params.put("owner_tel", txtOwnerTel.getText());
            params.put("owner_address", txtOwnerAddress.getText());
            params.put("daily_rent", Double.parseDouble(txtDailyRent.getText()));
            params.put("weekly_rent", Double.parseDouble(txtWeeklyRent.getText()));
            params.put("monthly_rent", Double.parseDouble(txtMonthlyRent.getText()));

        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(this, "Invalid data format entered", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (VehicleController.addNewVechicle(params)) {
            JOptionPane.showConfirmDialog(this, "New vehicle added successfully", "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);            
            btnAddNew.doClick();
            this.loadAllVehicles();
            tblMain.setRowSelectionInterval(0, 0);
            
        } else {
            JOptionPane.showConfirmDialog(this, "Failed to add new vehicle.\n\nError: " + VehicleController.ERROR_MESSAGE, "Add New Vehicle", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAddNew;
        private javax.swing.JButton btnClose;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnFind;
        private javax.swing.JButton btnHelp;
        private javax.swing.JButton btnSave;
        private javax.swing.JButton btnView;
        private javax.swing.JComboBox<String> cboType;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JSeparator jSeparator3;
        private javax.swing.JTable tblMain;
        private javax.swing.JTextField txtChassisNo;
        private javax.swing.JTextField txtDailyRent;
        private javax.swing.JTextField txtEngineNo;
        private javax.swing.JTextField txtMake;
        private javax.swing.JTextField txtMileage;
        private javax.swing.JTextField txtModel;
        private javax.swing.JTextField txtMonthlyRent;
        private javax.swing.JTextArea txtOwnerAddress;
        private javax.swing.JTextField txtOwnerName;
        private javax.swing.JTextField txtOwnerTel;
        private javax.swing.JTextField txtVehicleNo;
        private javax.swing.JTextField txtWeeklyRent;
        private javax.swing.JTextField txtYear;
        // End of variables declaration//GEN-END:variables
}
